### ISSUE TITLE
Recipes with multiple ingridients but no inShape

### ISSUE THREAD

**Issue by constantins2001** [PrismarineJS/prismarine-recipe#10]
Example:
Recipe for diamond_pickaxe in versions 1.9.4, 1.10.2 and 1.13.2 lists two ingridients but no inShape.
The crafting recipe in itself is invalid as the two ingridients are the ID of the result itself.

Causes new crafting tests in https://github.com/PrismarineJS/mineflayer/pull/2418 to fail.

**Comment by rom1504** [comment]
do you want to fix that in minecraft data ? (or @nickelpro maybe ?)

**Comment by nickelpro** [comment]
Needs to be covered in audit scripts, then we can identify all the offenders and fix them. Inshape should be a required field ya?

**Comment by constantins2001** [comment]
Would remove a piece of complexity in the crafting code :) 
Additionaly, I noticed that the delta is sometimes wrong (if I remember correctly for cake?)

**Comment by nickelpro** [comment]
In any case it doesn't appear to be a pris-recipe issue. This is a bad data issue
